# Generated by Django 2.0.1 on 2018-02-06 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_study_id', models.CharField(max_length=100)),
                ('nct_id', models.CharField(max_length=100)),
                ('official_title', models.CharField(max_length=100)),
                ('lead_sponsor_agency', models.CharField(max_length=100)),
                ('lead_sponsor_agency_class', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=500)),
                ('brief_summary', models.TextField()),
                ('detail_description', models.TextField()),
                ('overall_status', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('completion_date', models.CharField(max_length=100)),
                ('study_type', models.CharField(max_length=100)),
                ('no_of_arms', models.IntegerField(default=0)),
                ('no_of_enrollment', models.IntegerField(default=0)),
                ('enrollment_type', models.CharField(max_length=100)),
                ('eligibility_study_pop', models.TextField()),
                ('eligibility_sampling_method', models.CharField(max_length=100)),
                ('eligibility_criteria', models.TextField()),
                ('eligibility_gender', models.CharField(max_length=100)),
                ('eligibility_min_age', models.CharField(max_length=100)),
                ('eligibility_max_age', models.CharField(max_length=100)),
                ('overall_official_name', models.CharField(max_length=100)),
                ('overall_official_role', models.CharField(max_length=100)),
                ('overall_official_affiliation', models.CharField(max_length=100)),
                ('result_first_posted_date', models.CharField(max_length=100)),
                ('last_updated_date', models.CharField(max_length=100)),
                ('verification_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=200)),
                ('clinicalStudyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalSearch.ClinicalStudy')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_name', models.CharField(max_length=200)),
                ('intervention_type', models.CharField(max_length=200)),
                ('intervention_description', models.CharField(max_length=200)),
                ('clinicalStudyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalSearch.ClinicalStudy')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('location_status', models.CharField(max_length=100)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(max_length=100)),
                ('location_zip', models.CharField(max_length=100)),
                ('location_country', models.CharField(max_length=100)),
                ('clinicalStudyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalSearch.ClinicalStudy')),
            ],
        ),
        migrations.CreateModel(
            name='Mesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh_name', models.CharField(max_length=200)),
                ('clinicalStudyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalSearch.ClinicalStudy')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(max_length=200)),
                ('measure', models.TextField()),
                ('timeFrame', models.TextField()),
                ('description', models.TextField()),
                ('clinicalStudyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalSearch.ClinicalStudy')),
            ],
        ),
    ]
