# Generated by Django 2.0.1 on 2018-02-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalSearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='outcome_type',
            new_name='condition_name',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='timeFrame',
        ),
    ]
